### PR TITLE
fix #57 enforcer logic when there is no policy found

### LINKED ISSUE #57: An $expression variable is initialized with wrong type which results in fatal error
https://github.com/php-casbin/php-casbin/blob/8d6d87011f2c024af409d71534197c50c9767491/src/Enforcer.php#L556
A variable $expression is initialized as `ExpressionLanguage`, and then used as function argument where `Expression` is required. In most cases it is redefined by value returned from `$expressionLanguage->parse(...)` method, but in one case it is used unchanged:
https://github.com/php-casbin/php-casbin/blob/8d6d87011f2c024af409d71534197c50c9767491/src/Enforcer.php#L636
It results in a fatal error with message:
```
Object of class Symfony\Component\ExpressionLanguage\ExpressionLanguage could not be converted to string
```

### PR DESCRIPTION
**Pull request by yk17310320725**
Fix: https://github.com/php-casbin/php-casbin/issues/57

When your use `eval()` in matcher whthout use the policy.
@techoner please review.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@andbabkin @techoner please review.

**Comment by hsluoyz** [comment]
@yk17310320725 please fix StyleCI error:

image

**Comment by hsluoyz** [comment]
@andbabkin please review.

**Review by andbabkin — APPROVED** [review]
Looks good. It will save a lot of time to everyone who forget to provide ABAC policies before checking requests

**Comment by hsluoyz** [comment]
@techoner please review.

File: src/Enforcer.php [hunk 1]
```diff
@@ -557,7 +558,6 @@ protected function enforcing(string $matcher, ...$rvals): bool
         $hasEval = Util::hasEval($expString);
 
         if (!$hasEval) {
-            $expressionLanguage = $this->getExpressionLanguage($functions);
             $expression = $expressionLanguage->parse($expString, array_merge($rTokens, $pTokens));
```
Comment (techoner) [inline src/Enforcer.php:561]: `$expression`  is initialized as `ExpressionLanguage` at Line 557, could not be converted to string.

**Review by techoner — CHANGES_REQUESTED** [review]

File: src/Enforcer.php (hunk 1 above)
Comment (yk17310320725) [reply src/Enforcer.php:560]: Yes, Line 557 is redundant. I have deleted

**Comment by hsluoyz** [comment]
@techoner please review.
